/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletIndexRouteImport } from './routes/wallet/index'
import { Route as UploadIndexRouteImport } from './routes/upload/index'
import { Route as SurveyIndexRouteImport } from './routes/survey/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as CommentsIndexRouteImport } from './routes/comments/index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as CampaignIndexRouteImport } from './routes/Campaign/index'
import { Route as TransactionsTransactionsRouteImport } from './routes/transactions/transactions'
import { Route as CampaignHistoryCampaignHistoryRouteImport } from './routes/campaignHistory/campaignHistory'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadIndexRoute = UploadIndexRouteImport.update({
  id: '/upload/',
  path: '/upload/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyIndexRoute = SurveyIndexRouteImport.update({
  id: '/survey/',
  path: '/survey/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsIndexRoute = CommentsIndexRouteImport.update({
  id: '/comments/',
  path: '/comments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignIndexRoute = CampaignIndexRouteImport.update({
  id: '/Campaign/',
  path: '/Campaign/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsTransactionsRoute =
  TransactionsTransactionsRouteImport.update({
    id: '/transactions/transactions',
    path: '/transactions/transactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignHistoryCampaignHistoryRoute =
  CampaignHistoryCampaignHistoryRouteImport.update({
    id: '/campaignHistory/campaignHistory',
    path: '/campaignHistory/campaignHistory',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/campaignHistory/campaignHistory': typeof CampaignHistoryCampaignHistoryRoute
  '/transactions/transactions': typeof TransactionsTransactionsRoute
  '/Campaign': typeof CampaignIndexRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/comments': typeof CommentsIndexRoute
  '/posts': typeof PostsIndexRoute
  '/survey': typeof SurveyIndexRoute
  '/upload': typeof UploadIndexRoute
  '/wallet': typeof WalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/campaignHistory/campaignHistory': typeof CampaignHistoryCampaignHistoryRoute
  '/transactions/transactions': typeof TransactionsTransactionsRoute
  '/Campaign': typeof CampaignIndexRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/comments': typeof CommentsIndexRoute
  '/posts': typeof PostsIndexRoute
  '/survey': typeof SurveyIndexRoute
  '/upload': typeof UploadIndexRoute
  '/wallet': typeof WalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/campaignHistory/campaignHistory': typeof CampaignHistoryCampaignHistoryRoute
  '/transactions/transactions': typeof TransactionsTransactionsRoute
  '/Campaign/': typeof CampaignIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/comments/': typeof CommentsIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/survey/': typeof SurveyIndexRoute
  '/upload/': typeof UploadIndexRoute
  '/wallet/': typeof WalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/campaignHistory/campaignHistory'
    | '/transactions/transactions'
    | '/Campaign'
    | '/analytics'
    | '/comments'
    | '/posts'
    | '/survey'
    | '/upload'
    | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/campaignHistory/campaignHistory'
    | '/transactions/transactions'
    | '/Campaign'
    | '/analytics'
    | '/comments'
    | '/posts'
    | '/survey'
    | '/upload'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/campaignHistory/campaignHistory'
    | '/transactions/transactions'
    | '/Campaign/'
    | '/analytics/'
    | '/comments/'
    | '/posts/'
    | '/survey/'
    | '/upload/'
    | '/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CampaignHistoryCampaignHistoryRoute: typeof CampaignHistoryCampaignHistoryRoute
  TransactionsTransactionsRoute: typeof TransactionsTransactionsRoute
  CampaignIndexRoute: typeof CampaignIndexRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  CommentsIndexRoute: typeof CommentsIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  SurveyIndexRoute: typeof SurveyIndexRoute
  UploadIndexRoute: typeof UploadIndexRoute
  WalletIndexRoute: typeof WalletIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/': {
      id: '/upload/'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey/': {
      id: '/survey/'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments/': {
      id: '/comments/'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof CommentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Campaign/': {
      id: '/Campaign/'
      path: '/Campaign'
      fullPath: '/Campaign'
      preLoaderRoute: typeof CampaignIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/transactions': {
      id: '/transactions/transactions'
      path: '/transactions/transactions'
      fullPath: '/transactions/transactions'
      preLoaderRoute: typeof TransactionsTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaignHistory/campaignHistory': {
      id: '/campaignHistory/campaignHistory'
      path: '/campaignHistory/campaignHistory'
      fullPath: '/campaignHistory/campaignHistory'
      preLoaderRoute: typeof CampaignHistoryCampaignHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CampaignHistoryCampaignHistoryRoute: CampaignHistoryCampaignHistoryRoute,
  TransactionsTransactionsRoute: TransactionsTransactionsRoute,
  CampaignIndexRoute: CampaignIndexRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  CommentsIndexRoute: CommentsIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  SurveyIndexRoute: SurveyIndexRoute,
  UploadIndexRoute: UploadIndexRoute,
  WalletIndexRoute: WalletIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
